CREATE TABLE IF NOT EXISTS sessions (
  `id` String,
  `project_id` String CODEC(ZSTD(3)),
  `profile_id` String CODEC(ZSTD(3)),
  `device_id` String CODEC(ZSTD(3)),
  `created_at` DateTime64(3) CODEC(DoubleDelta, ZSTD(3)),
  `ended_at` DateTime64(3) CODEC(DoubleDelta, ZSTD(3)),
  `is_bounce` Bool,
  `entry_origin` LowCardinality(String),
  `entry_path` String CODEC(ZSTD(3)),
  `exit_origin` LowCardinality(String),
  `exit_path` String CODEC(ZSTD(3)),
  `screen_view_count` Int32,
  `revenue` Float64,
  `event_count` Int32,
  `duration` UInt32,
  `country` LowCardinality(FixedString(2)),
  `region` LowCardinality(String),
  `city` String,
  `longitude` Nullable(Float32) CODEC(Gorilla, LZ4),
  `latitude` Nullable(Float32) CODEC(Gorilla, LZ4),
  `device` LowCardinality(String),
  `brand` LowCardinality(String),
  `model` LowCardinality(String),
  `browser` LowCardinality(String),
  `browser_version` LowCardinality(String),
  `os` LowCardinality(String),
  `os_version` LowCardinality(String),
  `utm_medium` String CODEC(ZSTD(3)),
  `utm_source` String CODEC(ZSTD(3)),
  `utm_campaign` String CODEC(ZSTD(3)),
  `utm_content` String CODEC(ZSTD(3)),
  `utm_term` String CODEC(ZSTD(3)),
  `referrer` String CODEC(ZSTD(3)),
  `referrer_name` String CODEC(ZSTD(3)),
  `referrer_type` LowCardinality(String),
  `sign` Int8,
  `version` UInt64,
  `properties` Map(String, String) CODEC(ZSTD(3))
)
ENGINE = VersionedCollapsingMergeTree(sign, version)
PARTITION BY toYYYYMM(created_at)
ORDER BY (project_id, id, toDate(created_at), profile_id)
SETTINGS index_granularity = 8192;